apiVersion: v1
kind: Namespace
metadata:
  name: demo-mesh             # <--- 2 espacios de sangría
  labels:                     # <--- 2 espacios de sangría
    istio-injection: enabled  # <--- 4 espacios de sangría
